# Generated by Django 5.2.4 on 2025-07-22 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_add_promo_and_shipping'),
        ('store', '0008_alter_order_status'),
    ]

    operations = [
    ]
