# Generated by Django 5.2.4 on 2025-07-22 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_merge_20250722_1518'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promocode',
            options={'verbose_name': 'Code Promo', 'verbose_name_plural': 'Codes Promo'},
        ),
        migrations.AddField(
            model_name='product',
            name='shipping_fee_bulk',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Frais livraison (gros)'),
        ),
        migrations.AddField(
            model_name='product',
            name='shipping_fee_unit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Frais livraison unitaire'),
        ),
    ]
