# Generated by Django 5.2.4 on 2025-07-16 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='error_message',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='payment',
            name='processor',
            field=models.CharField(choices=[('cinetpay', 'CinetPay'), ('stripe', 'Stripe'), ('manual', 'Manuel')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='processor_response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='processor_token',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='payment',
            name='processor_transaction_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
